### PR TITLE
[fix] responsive layout for city index and detail city page

### LINKED ISSUE #33: 【社区组织者】 优化页面布局
https://fcc-china.vercel.app/organizer
1. 【社区组织者】 标题居中；
2.  每个头像组件之间应该有合理的间距：
     

3.  头像组件溢出

### PR DESCRIPTION
**Pull request by PapayaHUANG**
- [x] Labels
- [ ] Assignees
- [x] Reviewers

closes #33

### CODE REVIEW

File: components/PersonCard.tsx [hunk 1]
```diff
@@ -1,24 +1,35 @@
...
-import { Card } from 'react-bootstrap';
+import { Card, Col } from 'react-bootstrap';
 
 export type PersonCardProps = {
   avatar: string;
-  name?: string;
+  name: string;
+  link?: string;
+  position?: string;
+  key: number;
```
Comment (TechQuery) [inline components/PersonCard.tsx:9]:
```suggestion
```
React 内置属性，Props 控制不了

File: components/conference/Guest.tsx [hunk 2]
```diff
@@ -1,34 +1,22 @@
...
-            />
-            <ul className="list-unstyled mt-3">
-              <li className="fs-6 fw-bolder mt-1">{name}</li>
-              <li className="mt-1">{position}</li>
-            </ul>
-          </Col>
-        ))}
-      </Row>
-    </section>
+  <Container className="text-center mx-auto my-0">
```
Comment (TechQuery) [inline components/conference/Guest.tsx:8]:
```suggestion
  <Container as="section" className="text-center mx-auto my-0">
```

File: components/conference/Guest.tsx [hunk 3]
```diff
@@ -1,34 +1,22 @@
...
+    <h2 id="guests" className="fs-4 m-0 py-5">
+      演讲嘉宾（持续更新）
+    </h2>
+    <Row as="ul" className="list-unstyled" xs={2} sm={4}>
+      {guestData.map(({ pic, name, position }, index) => (
+        <PersonCard
+          avatar={`/image/speaker/${pic}`}
+          key={index}
```
Comment (TechQuery) [inline components/conference/Guest.tsx:16]:
```suggestion
      {guestData.map(({ pic, name, position }) => (
        <PersonCard
          key={name}
          avatar={`/image/speaker/${pic}`}
```
`key` 要**界面顺序无关**、唯一不可变

File: pages/organizer/index.tsx [hunk 4]
```diff
@@ -10,19 +10,22 @@ const organizers = Object.values(data).flatMap(({ organizers }) => organizers);
...
+      xs={2}
+      sm={5}
+      md={6}
+    >
+      {organizers.map(({ name, link, pic }, index) => (
+        <PersonCard
+          avatar={`/image/organizer/${pic}`}
+          link={`/organizer/${link}` || '#'}
+          key={index}
+          {...{ name }}
```
Comment (TechQuery) [inline pages/organizer/index.tsx:27]: 单个属性没必要这样

**Review by TechQuery — CHANGES_REQUESTED** [review]

**Review by TechQuery — APPROVED** [review]
